version: "3.4"

services:
  backendpethomeapi:
    image: backendpethomeapi
    restart: on-failure
    build:
      context: .
      dockerfile: backendPetHome/Dockerfile
    networks:
      - back
    ports:
      - "8080:80"
    depends_on:
      - petHomeDB
    environment:
      ConnectionStrings__DefaultConnection: "server=petHomeDB;database=testdb;User=sa;password=Password123!"
      LANG: uk_UA.UTF-8
      LANGUAGE: uk_UA
      LC_ALL: uk_UA.UTF-8

  petHomeDB:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    networks:
      - back
    environment:
      SA_PASSWORD: "Password123!"
      ACCEPT_EULA: "Y"

networks:
  back:
    driver: bridge
