name: Docker images
on:
  push:
    branches: [main]
jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push backend docker image
        uses: docker/build-push-action@v3
        with:
          context: ./backendPetHome
          file: ./backendPetHome/backendPetHome/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend-pet-home:latest
          push: true
          build-args: |
            PROJECT_PORT=80
